### ISSUE TITLE
16-bit C compiler runs "out of memory"

### ISSUE THREAD

**Issue by stephanosio** [stephanosio/MinNT#20]
All DOS components (mvdm\dos\v86\*) build now except mem (mvdm\dos\v86\mem).

The following is the error:
![image](https://cloud.githubusercontent.com/assets/11345418/24836579/2b120544-1d5a-11e7-8397-0efb5d24124d.png)

I've tried both compiler version 8.00x (included with NT 4.0 tools16) and 8.00c (included with NT 5.2 tools16) and they behave identically. This issue should be further investigated in the future.

NOTE: That "BUGFIX switch is ON" message is not from the compiler itself and is rather from version.h. The real issue is that it runs "out of memory."

**Comment by stephanosio** [comment]
This issue isn't just specific to MEM. This seems to happen to most applications that contains C source code (and hence, use C compiler). So far, we've verified this issue happening with MEM and SETVER.

However, it is important to note that the buildmsg.exe compilation using the same compiler during COMMAND build process succeeds (no out of memory error) and the produced executable successfully runs. So it doesn't simply seem to be a faulty compiler, or path-related issue. I mean this is the same compiler we used to build DOS and WoW16 components in NT 4.

This must be some kind of compatibility issue with modern Windows (I'm currently using Windows 10 1607 AMD64). NT 5.x users are welcome to test this out on their versions of Windows and see if this issue is reproducible.

**Comment by MasonLeeBack** [comment]
I'm running the same build of Windows as you (Although I'm running Windows Server), however, I don't get the exact same issue as you. The application seems to crash instead of saying that it's out of memory.
![image](https://cloud.githubusercontent.com/assets/12467547/24840844/78cee548-1d43-11e7-8a5d-0d4e3604c085.png)

**Comment by stephanosio** [comment]
Hmm, I am not sure what exactly the issue is at the moment. One thing is for sure: these components used to compile just fine in old-src repository. We should run NTOSBE under x86 NT 5.2 to see if it behaves in the same way. Unfortunately, I don't have a NT 5.2 VM ready to go now.

**Comment by stephanosio** [comment]
Also just in case, try the compiler version 8.00x on your machine and see if the same thing happens just in case.

**Comment by MasonLeeBack** [comment]
![image](https://cloud.githubusercontent.com/assets/12467547/24843250/031e8534-1d6f-11e7-9ca6-25d72e0a69ba.png)
It seems to work fine on NT 5.2, I'm just going to assume the error is because I didn't build other components first.

**Comment by MasonLeeBack** [comment]
8.00x has no difference. 
![image](https://cloud.githubusercontent.com/assets/12467547/24843443/eedc5b58-1d70-11e7-90fc-23319d48dece.png)

**Comment by stephanosio** [comment]
Given that the compiler, at least, doesn't crash on NT 5.2, it is very likely that the issue has something to do with Windows 10 compatibility. I will try debugging the compiler when I manage to spare some free time for this.

**Comment by stephanosio** [comment]
Regarding buildmsg compilation during COMMAND build process, some abnormality was discovered.
"cl16 /Zl /Gs -c -IUSA -I..\..\h -FoUSA\objchk\x86\buildmsg.obj buildmsg.c" succeeds with the compiler version 8.00x, but fails with 8.00c.
![image](https://cloud.githubusercontent.com/assets/11345418/24887013/e35be9aa-1e93-11e7-803a-5d54949a84f4.png)

**Comment by stephanosio** [comment]
I think we, sort of, figured out what is causing this issue. First of all, the issue does have something to do with path; in particular, the length of the compiler executable file path (and possibly source code file too since mem.c fails while buildmsg.c succeeds using the same compiler).

I've moved the NTOSBE tools16 directory to a relatively short path (from 'D:\OpenNT\Repositories\NTOSBE.master\tools\x86\tools16' to 'D:\test\tools16') and mem.c now successfully compiles.

![image](https://cloud.githubusercontent.com/assets/11345418/24887284/93c8c1f4-1e95-11e7-9d55-adad1435059c.png)

Looks like we will have to reverse and modify the compiler executables to increase the buffer size.

**Comment by MasonLeeBack** [comment]
I'll see if I can do anything about that. In the cl16 file, there is a variable that goes like this:
CHAR Filename[260], but I doubt that's what we're looking for.

**Comment by stephanosio** [comment]
Another interesting point:
PATH environment variable also seems to have something to do with it. When I shortened the PATH environment variable length, the compiler managed to successfully produce an object file.
![image](https://cloud.githubusercontent.com/assets/11345418/24891944/18cf737a-1eb4-11e7-9dd7-0b276fa7f1a6.png)

**Comment by stephanosio** [comment]
The compiler has some kind of internal pre-allocated memory pool and the error was caused by the memory pool running out of space. I've traced down the function that allocates this memory pool and increased the initial allocation size from 8000 bytes to 16000 bytes. After this patch, the compilation successfully proceeds.

**Comment by MasonLeeBack** [comment]
I seem to be having an issue with the 16-bit compiler, causing it to give an error (0xc0000005)
I'm unsure of what is giving this error and it needs investigated.

![image](https://cloud.githubusercontent.com/assets/12467547/26532051/5c2c4de2-43c5-11e7-9d23-56d012b21984.png)

**Comment by MasonLeeBack** [comment]
EDIT: After further investigation, it was calling the wrong compiler.
