### ISSUE TITLE
Add SMSS

### ISSUE THREAD

**Issue by stephanosio** [stephanosio/MinNT#3]
Add SMSS component to MinNT repository.

The exact placement of this component in the repository is to be determined in the future.

**Comment by MasonLeeBack** [comment]
Would SMSS component use the \tools\gs_support\ in the minkernel directory or would it use bufferoverflow.lib? I don't have a complete implementation of the gs_support if that's the case.

**Comment by stephanosio** [comment]
For now, gs_support should be implemented using BufferOverflow(U).lib in case of SMSS. Alternatively, you could simply disable gs_support by adding BUFFER_OVERFLOW_CHECKS=0 for now.

**Comment by stephanosio** [comment]
1>NMAKE :  U1073: don't know how to make 'F:\OpenNT\Repositories\MinNT.master\public\sdk\lib\x86\nt.lib'

**Comment by MasonLeeBack** [comment]
I'll start merging urtl now.

**Comment by MasonLeeBack** [comment]
Seeing as SMSS is added to the repository now, I will close this issue.
